name: CI GitHub Runners

on: 
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main 

jobs:
  ActionsVM:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    env:
      GH_JOBNAME: ${{ matrix.jobname }}
      GH_OS: Linux
    strategy:
      fail-fast: false 
      matrix:
        jobname: [
          ubuntu20-julia1.7.3]
    
    steps:
    - name: Verify Julia
      run: julia --version

    - name: Checkout Action
      uses: actions/checkout@v3   #v3 is the latest 
    
    - name: Instantiate 
      run: |
       echo $GITHUB_WORKSPACE 
       cd $GITHUB_WORKSPACE 
       julia --project -e 'using Pkg; Pkg.instantiate();'
    
    - name: Test
      run: julia --project test/runtests.jl

  Docker:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    env:
      GH_JOBNAME: ${{ matrix.jobname }}
      GH_OS: Linux
    strategy:
      fail-fast: false 
      matrix:
        jobname: [Ubuntu22]
        include:
        - jobname: Ubuntu22
          container: alexianoele/docker_riopa:ubuntu22
         
    steps:
    - name: Verify Julia
      run: julia --version

    - name: Checkout Action
      uses: actions/checkout@v3   #v3 is the latest 
    
    - name: Instantiate 
      run: |
       echo $GITHUB_WORKSPACE 
       cd $GITHUB_WORKSPACE 
       julia --project -e 'using Pkg; Pkg.instantiate();'
    
    - name: Test
      run: julia --project test/runtests.jl
